CREATE SCHEMA `aluguelcarros` ;
USE aluguelcarros;

CREATE TABLE pessoa (
	CPF CHAR(11) NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    PRIMARY KEY (CPF)
);

CREATE TABLE cliente (
	CPF CHAR(11) NOT NULL,
    IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (IDCLIENTE),
    FOREIGN KEY (CPF) REFERENCES pessoa(CPF)
);

CREATE TABLE funcionario (
	CPF CHAR(11) NOT NULL,
    IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    ANOCONT DATE NOT NULL,
    SALARIO DOUBLE NOT NULL,
    PRIMARY KEY (IDFUNCIONARIO),
    FOREIGN KEY (CPF) REFERENCES pessoa(CPF)
);

CREATE TABLE caminhoneiro (
    IDCAMINHONEIRO INT NOT NULL AUTO_INCREMENT,
    IDFUNCIONARIO INT NOT NULL,
    CNH CHAR(11) NOT NULL,
    TIPOCNH CHAR(1) NOT NULL,
    PRIMARY KEY (IDCAMINHONEIRO),
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE filial	 (
    IDFILIAL INT NOT NULL AUTO_INCREMENT,
    LOCALIZACAO VARCHAR(200) NOT NULL,
    HORFUNC VARCHAR(200) NOT NULL,
    CAPACIDADECARROS INT NOT NULL,
    PRIMARY KEY (IDFILIAL)
);

CREATE TABLE agente (
    IDAGENTE INT NOT NULL AUTO_INCREMENT,
    IDFUNCIONARIO INT NOT NULL,
    STATUSGERENTE BOOLEAN NOT NULL,
	IDFILIAL INT NOT NULL,
    PRIMARY KEY (IDAGENTE),
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
    FOREIGN KEY (IDFILIAL) REFERENCES  FILIAL(IDFILIAL)
);

CREATE TABLE gerencia (
    IDAGENTE INT NOT NULL,
    IDGERENTE INT NOT NULL,
    FOREIGN KEY (IDAGENTE) REFERENCES AGENTE(IDAGENTE),
    FOREIGN KEY (IDGERENTE) REFERENCES AGENTE(IDAGENTE)
);

CREATE TABLE parceiro (
    IDPARCEIRO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    INICIOPARCERIA DATE NOT NULL,
    FIMPARCERIA DATE,
	IDFILIAL INT NOT NULL,
    PRIMARY KEY (IDPARCEIRO),
    FOREIGN KEY (IDFILIAL) REFERENCES  FILIAL(IDFILIAL)
);

CREATE TABLE aeroporto (
    IDAEROPORTO INT NOT NULL AUTO_INCREMENT,
    IDPARCEIRO INT NOT NULL,
    DESCONTO DOUBLE NOT NULL,
    LOCALIZACAO VARCHAR(200) NOT NULL,
    PRIMARY KEY (IDAEROPORTO),
    FOREIGN KEY (IDPARCEIRO) REFERENCES  PARCEIRO(IDPARCEIRO)
);

CREATE TABLE redehoteis (
    IDREDEHOTEIS INT NOT NULL AUTO_INCREMENT,
    IDPARCEIRO INT NOT NULL,
    PRIMARY KEY (IDREDEHOTEIS),
    FOREIGN KEY (IDPARCEIRO) REFERENCES  PARCEIRO(IDPARCEIRO)
);

CREATE TABLE hotel (
	IDHOTEL INT NOT NULL AUTO_INCREMENT,
	IDREDEHOTEIS INT NOT NULL,
    DESCONTO DOUBLE NOT NULL,
    LOCALIZACAO VARCHAR(200) NOT NULL,
    PRIMARY KEY (IDHOTEL),
    FOREIGN KEY (IDREDEHOTEIS) REFERENCES  REDEHOTEIS(IDREDEHOTEIS)
);

CREATE TABLE garagem (
	IDGARAGEM INT NOT NULL AUTO_INCREMENT,
    LOCALIZACAO VARCHAR(200) NOT NULL,
	CAPACIDADECARROS INT NOT NULL,
    CAPACIDADECAMINHOES INT NOT NULL,
    PRIMARY KEY (IDGARAGEM)
);

CREATE TABLE carro (
	IDCARRO INT NOT NULL AUTO_INCREMENT,
	IDGARAGEM INT NOT NULL,
    FABRICANTE VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
	ANO INT NOT NULL,
    COR VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDCARRO),
    FOREIGN KEY (IDGARAGEM) REFERENCES GARAGEM(IDGARAGEM)
);

CREATE TABLE caminhao (
	IDCAMINHAO INT NOT NULL AUTO_INCREMENT,
	IDGARAGEM INT NOT NULL,
    FABRICANTE VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
	ANO INT NOT NULL,
    PRIMARY KEY (IDCAMINHAO),
    FOREIGN KEY (IDGARAGEM) REFERENCES GARAGEM(IDGARAGEM)
);

CREATE TABLE estacaomanutencao (
	IDESTACAO INT NOT NULL AUTO_INCREMENT,
    LOCALIZACAO VARCHAR(200),
    HORFUNC VARCHAR(200) NOT NULL,
    PRIMARY KEY (IDESTACAO)
);

CREATE TABLE servicos (
	SERVICO VARCHAR(200) NOT NULL,
    IDESTACAO INT NOT NULL,
    FOREIGN KEY (IDESTACAO) REFERENCES ESTACAOMANUTENCAO(IDESTACAO)
);

CREATE TABLE manutencao (
	IDMANUTENCAO INT NOT NULL AUTO_INCREMENT,
	IDESTACAO INT NOT NULL,
    ENTRADA DATE NOT NULL,
    SAIDA DATE NOT NULL,
    PRIMARY KEY (IDMANUTENCAO),
    FOREIGN KEY (IDCARRO) REFERENCES CARRO(IDCARRO),
    FOREIGN KEY (IDESTACAO) REFERENCES ESTACAOMANUTENCAO(IDESTACAO)
);

CREATE TABLE aluguel (
	IDALUGUEL INT NOT NULL AUTO_INCREMENT,
    IDCARRO INT NOT NULL,
    IDCLIENTE INT NOT NULL,
    RETIRADA DATE NOT NULL,
    RETORNO DATE NOT NULL,
    PRIMARY KEY (IDALUGUEL),
    FOREIGN KEY (IDCARRO) REFERENCES CARRO(IDCARRO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);


